version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout
      - run:
          name: Update pip
          command: pip install --upgrade pip
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest --html=report.html --self-contained-html

workflows:
  version: 2
  sample:
    jobs:
      - build-and-test
